import Foundation
import CoreGraphics

let internalDisplay = ScalingDisplay(id: 1, frame: CGRect(x: 0, y: 0, width: 1470, height: 956), builtIn: true)
let externalDisplay = ScalingDisplay(id: 3, frame: CGRect(x: 1470, y: 0, width: 1920, height: 1080), builtIn: false)
let displays = [internalDisplay, externalDisplay]
precondition(ScreenScalingPolicy.display(for: CGRect(x: 100, y: 100, width: 900, height: 700), displays: displays) == internalDisplay)
precondition(ScreenScalingPolicy.display(for: CGRect(x: 1700, y: 100, width: 900, height: 700), displays: displays) == externalDisplay)
precondition(ScreenScalingPolicy.display(for: CGRect(x: 1400, y: 100, width: 900, height: 700), displays: displays) == externalDisplay, "use greatest overlap, not top-left corner")
precondition(ScreenScalingPolicy.display(for: CGRect(x: 1020, y: 100, width: 900, height: 700), displays: displays) == nil, "exactly straddling a boundary must wait")
precondition(ScreenScalingPolicy.display(for: .zero, displays: displays) == nil)
precondition(ScreenScalingPolicy.display(for: CGRect(x: 4000, y: 100, width: 500, height: 500), displays: displays) == nil)
let aboveLeft = ScalingDisplay(id: 4, frame: CGRect(x: -1920, y: -1080, width: 1920, height: 1080), builtIn: false)
precondition(ScreenScalingPolicy.display(for: CGRect(x: -1500, y: -900, width: 900, height: 700), displays: [internalDisplay, aboveLeft]) == aboveLeft)
precondition(ScreenScalingPolicy.display(for: externalDisplay.frame, displays: displays) == externalDisplay, "Dock surface follows its own host display")
precondition(abs(ScreenScalingPolicy.normalizedDockSize(36) - 0.17857143) < 0.00001)
precondition(abs(ScreenScalingPolicy.normalizedDockSize(56) - 0.35714287) < 0.00001)
precondition(ScreenScalingPolicy.normalizedDockSize(-1) == 0)
precondition(ScreenScalingPolicy.normalizedDockSize(200) == 1)

var tracker = ScreenStabilityTracker()
let a = StableScreenCandidate(displayID: 1, frame: CGRect(x: 100, y: 100, width: 900, height: 700))
let b = StableScreenCandidate(displayID: 3, frame: CGRect(x: 1700, y: 100, width: 900, height: 700))
precondition(!tracker.ready(key: "app", candidate: a, now: 0, mouseDown: false))
precondition(!tracker.ready(key: "app", candidate: a, now: 0.4, mouseDown: false))
precondition(tracker.ready(key: "app", candidate: a, now: 0.5, mouseDown: false))
precondition(!tracker.ready(key: "app", candidate: b, now: 1, mouseDown: true))
precondition(!tracker.ready(key: "app", candidate: b, now: 2, mouseDown: false))
precondition(tracker.ready(key: "app", candidate: b, now: 2.5, mouseDown: false))
tracker.retain(keys: [])
precondition(!tracker.ready(key: "app", candidate: b, now: 4, mouseDown: false), "disappearing windows must settle again")
let moved = StableScreenCandidate(displayID: 3, frame: CGRect(x: 1701, y: 100, width: 900, height: 700))
precondition(!tracker.ready(key: "app", candidate: moved, now: 4.6, mouseDown: false), "moving within the same display also waits")
tracker.reset()
precondition(!tracker.ready(key: "app", candidate: moved, now: 6, mouseDown: false))
let options = try JSONDecoder().decode(AutomaticScreenScaling.self, from: Data("{\"applications\":true,\"dock\":false}".utf8))
precondition(options.applications && !options.dock)
let externalVisible = CGRect(x: 1470, y: -42, width: 1920, height: 998)
let alertSize = CGSize(width: 440, height: 240)
let externalPrompt = ScreenPromptPlacement.frame(size: alertSize, visibleFrame: externalVisible)
precondition(externalPrompt == CGRect(x: 2210, y: 337, width: 440, height: 240), "alert centers on external screen, including Dock reservation")
precondition(externalVisible.contains(externalPrompt), "external prompt must stay on external screen")
let internalPrompt = ScreenPromptPlacement.frame(size: alertSize, visibleFrame: CGRect(x: 0, y: 56, width: 1470, height: 867))
precondition(internalPrompt == CGRect(x: 515, y: 369.5, width: 440, height: 240))
let upperLeft = CGRect(x: -1920, y: 956, width: 1920, height: 1047)
precondition(upperLeft.contains(ScreenPromptPlacement.frame(size: alertSize, visibleFrame: upperLeft)), "display above/left of primary")
let tiny = CGRect(x: 100, y: 200, width: 300, height: 180)
precondition(ScreenPromptPlacement.frame(size: alertSize, visibleFrame: tiny) == tiny, "constrain prompt to a small display")
print("Screen scaling geometry, stability, Dock size, JSON and prompt placement: 27 checks passed.")
